name: Setup environment
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Cache pipenv
      uses: actions/cache@v4
      with:
          path: |
            ~/.cache/pip
            .venv
          key: pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            pipenv-

    - run: pip install pipenv
      shell: bash
    - run: pipenv install
      env:
        PIPENV_VENV_IN_PROJECT: "1"
      shell: bash